-- Add Buhs Emotes
BuhEmotesPack_defaultpack = {
	--Example
	--["EmoteName"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\EmoteName.tga:yy:xx",

	["pokiLoser"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\pokiLoser.tga:28:28",
	["Cinema"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Cinema.tga:28:74",
	["kittenlover"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\kittenlover.tga:28:28",
	["Lemon"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Lemon.tga:28:28",
	["lule"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\lule.tga:28:28",
	["PAYUP"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\PAYUP.tga:28:28",
	["COIN"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\COIN.tga:28:30",
	["Coins"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Coins.tga:28:28",
	["WalterIsSus"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WalterIsSus.tga:28:28",
	["forsenNugget"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenNugget.tga:28:21",
	["Speechless"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Speechless.tga:28:29",
	["bbL"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\bbL.tga:28:28",
	["forsenMissing"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenMissing.tga:28:28",
	["BeerTime"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\BeerTime.tga:28:28",
	["GETOUTTAHERE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\GETOUTTAHERE.tga:28:42",
	["forsenTRICKLEIN"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenTRICKLEIN.tga:28:44",
	["CoinTime"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\CoinTime.tga:28:24",
	["ome2"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\ome2.tga:28:28",
	["ome"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\ome.tga:28:28",
	["creature"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\creature.tga:28:28",
	["Coinge"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Coinge.tga:28:36",

    ["buh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\buh.tga:28:28",
	["Gigachad"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Gigachad.tga:28:28",
	["Buhh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Buhh.tga:28:28",
	["cuteBuhh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\cuteBuhh.tga:28:28",
	["buhL"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\buhL.tga:28:28",
	["forsen"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsen.tga:40:40",
	["Ted"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Ted.tga:28:28",
	["huh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\huh.tga:28:28",
	["docnotL"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docNotL.tga:28:28",
	["Ogre"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Ogre.tga:32:64",
	["NOOO"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\NOOO.tga:28:28",
	["Buhsiness"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Buhsiness.tga:32:64",
	["buhFriend"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\buhFriend.tga:28:28",
	["AYAYA"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\AYAYA.tga:28:28",
	["hesRight"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hesRight.tga:28:28",
	["nymnVibe"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\nymnVibe.tga:28:28",
	["MUGA"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\MUGA.tga:32:64",
	["chipichipi"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\chipichipi.tga:28:28",
	["corpa"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\corpa.tga:28:28",
	["docL"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docL.tga:28:28",
	["WAYTOOBUH"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WAYTOOBUH.tga:28:28",
	--["OOOO"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\OOOO.tga:32:64",
	["OOOO"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\OOOO.tga:32:64",
	["WHAT"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WHAT.tga:28:28",
	["forsenMaxLevel"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenMaxLevel.tga:28:28",
	["veryCat"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\veryCat.tga:28:28",
	["terryBased"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\terryBased.tga:28:28",
	["docBozo"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docBozo.tga:28:28",
	--["hiii"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hiii.tga:28:28",
	["Tomfoolery"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Tomfoolery.tga:28:28",
	["AmongE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\AmongE.tga:28:28",
	["buhNOW"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\buhNOW.tga:28:28",
	["Mails"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Mails.tga:28:28",
	["billyApprove"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\billyApprove.tga:28:28",
	["forsenLaughingAtYou"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenLaughingAtYou.tga:28:28",
	["hesBB"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hesBB.tga:28:28",
	["eliselis"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\eliselis.tga:28:28",
	["WeebsOut"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WeebsOut.tga:28:28",
	["glorp"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\glorp.tga:28:28",
	["glorpLove"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\glorpLove.tga:28:28",
	["glebeGlebe"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\glebeGlebe.tga:28:28",
	["NOIDONTTHINKSO"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\NOIDONTTHINKSO.tga:28:28",
	["billySmoke"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\billySmoke.tga:28:28",
	["docSpin"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docSpin.tga:28:28",
	["hiii"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hiii.tga:28:28",
	["peachy"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\peachy.tga:28:28",
	["doctorWTF"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\doctorWTF.tga:28:28",
	["Despair"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Despair.tga:28:28",
	["angrE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\angrE.tga:28:28",
	["CAUGHT"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\CAUGHT.tga:32:64",
	["happyHobo"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\happyHobo.tga:28:28",
	["FeelsDonkMan"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\FeelsDonkMan.tga:28:28",
	["forsenInsane"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenInsane.tga:28:28",
	["Jackass"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Jackass.tga:28:28",
	["RaidToday"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\RaidToday.tga:28:128",
	["Rime"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Rime.tga:28:28",
	["waltuh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\waltuh.tga:28:28",
	["Waltuhwhite"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\waltuh.tga:28:28",
	["docRant"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docRant.tga:28:28",
	["forsenCoomer"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenCoomer.tga:28:28",
	["MAXWIN"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\MAXWIN.tga:28:64",
	["NOWWHAT"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\NOWWHAT.tga:28:28",
	["plink"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\plink.tga:28:28",
	["Scared"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Scared.tga:28:28",
	["confused"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\confused.tga:28:28",
	["floppaHey"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\floppaHey.tga:28:28",
	["poroSad"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\poroSad.tga:28:28",
	["poroBuff"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\poroBuff.tga:28:28",
	["Roppie"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Roppie.tga:28:28",
	["sadE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\sadE.tga:28:28",
	["terrypls"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\terrypls.tga:28:28",
	["AINTNOWAY"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\AINTNOWAY.tga:28:28",
	
	["DOCING"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\DOCING.tga:28:28",
	["DRAMA"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\DRAMA.tga:28:28",
	["4House"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\4House.tga:28:28",
	["AlienUnpleased"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\AlienUnpleased.tga:28:28",
	["Dutch"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Dutch.tga:28:28",
	["Erizel"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Erizel.tga:28:48",
	["EULKEKUNJEF"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\EULKEKUNJEF.tga:28:28",
	["forsenOhiomaxcape"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenOhiomaxcape.tga:28:28",
	["Hipposham"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Hipposham.tga:28:28",
	["Hippan"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Hipposham.tga:28:28",
	["KUKLE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\KUKLE.tga:28:28",
	["LEUL"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\LEUL.tga:28:28",
	["NIME"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\NIME.tga:28:28",
	["ULLE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\ULLE.tga:28:28",
	["zazabert"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\zazabert.tga:28:64",
	["forsenLevel"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenLevel.tga:28:28",
	["HowAboutYouShutYourMouthUp"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\HowAboutYouShutYourMouthUp.tga:28:28",
	["IHATEAI"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\IHATEAI.tga:28:28",
	["Alienapprove"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Alienapprove.tga:28:28",
	["Lexmorn"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Alienapprove.tga:28:28",
	["MODS"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\MODS.tga:28:28",
	["OMEGALULiguess"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\OMEGALULiguess.tga:28:28",
	["Pepepainsiguess"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Pepepainsiguess.tga:28:28",
	["Sneak"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Sneak.tga:28:28",
	
	["AlienDisapointedInYou"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\AlienDisapointedInYou.tga:28:28",
	["AlienL"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\AlienL.tga:28:28",
	["angriER"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\angriER.tga:28:28",
	["looking"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\looking.tga:28:28",
	["FRICK"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\FRICK.tga:28:28",
	["hesRetarded"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hesRetarded.tga:28:28",
	["LULG"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\LULG.tga:28:28",
	["peepoTalkbutpeepoisnottalking"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\peepoTalkbutpeepoisnottalking.tga:28:28",
	["Pointless"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Pointless.tga:28:28",
	["Sadeg"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Sadeg.tga:28:28",
	["Smile"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Smile.tga:28:28",
	["ta"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\ta.tga:32:32",
	["ta7"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\ta7.tga:32:32",
	["tuh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\tuh.tga:32:32",
	["Aplonk"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Aplonk.tga:28:28",
	["Dreiecksmann"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Dreiecksmann.tga:28:28",
	["Erm"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Erm.tga:28:28",
	["forsenExplainingHow"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenExplainingHow.tga:28:28",
	["forsenHoppedIn"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenHoppedIn.tga:28:28",
	["hump"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hump.tga:28:28",
	["Kronvall"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Kronvall.tga:28:28",
	["OHMYGOD"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\OHMYGOD.tga:28:28",

	["WHATTAAHFUCK"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WHATTAAHFUCK.tga:28:28",
	["wuh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\wuh.tga:28:28",
	["tassemble"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\tassemble.tga:28:28",
	["tatter"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\tatter.tga:28:28",
	["Drunkge"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Drunkge.tga:32:48",
	["tay"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\tay.tga:32:32",
	["xalatath"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\xalatath.tga:64:64",
	["tah"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\tah.tga:32:32",
	["Blalatath"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Blalatath.tga:32:32",

	["oopsie"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\oopsie.tga:28:28",
	["clappi"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\clappi.tga:28:28",
	["Despairm"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Despairm.tga:28:28",
	["er"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\er.tga:28:20",
	["eww"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\eww.tga:28:28",
	["forsenAlright"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenAlright.tga:28:28",
	["hesGripping"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hesGripping.tga:28:40",
	["ta0"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\ta0.tga:28:28",
	["waiting"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\waiting.tga:28:48",
	["catSigh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\catSigh.tga:28:28",
	["sus"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\sus.tga:28:28",
	["tainy"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\tainy.tga:28:32",
	["500cigarettes"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\500cigarettes.tga:28:28",
	["catWait"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\catWait.tga:28:28",
	["erm"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\ermgamba.tga:28:28",
	["Ermki"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Ermki.tga:28:28",
	["GULP"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\GULP.tga:28:28",
	["IHaveBrainDamage"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\IHaveBrainDamage.tga:28:28",
	["keking"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\keking.tga:28:28",
	["Pffttt"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Pffttt.tga:28:28",
	["prePffttt"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\prePffttt.tga:28:28",
	["vegan"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\vegan.tga:28:28",
	["wait"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\wait.tga:28:28",
	--["YoungMan"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\YoungMan.tga:28:28",
	["forsenbitrate"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenbitrate.tga:28:28",
	--["YesThisIsTheTwoTimes"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\YesThisIsTheTwoTimes.tga:28:28",
	["cokebert"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\cokebert.tga:28:84",
	["crackbert"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\crackbert.tga:28:59",

	["Aloo"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Aloo.tga:28:28",
	["chicanery"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\chicanery.tga:28:28",
	["forsenFaint"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenFaint.tga:28:28",
	["glorpFaint"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\glorpFaint.tga:28:28",
	["kok"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\kok.tga:28:28",
	["Lamonting"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Lamonting.tga:28:28",
	["mhm"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\mhm.tga:28:28",
	["nuhuh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\nuhuh.tga:28:28",
	["poroAgony"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\poroAgony.tga:28:28",
	["poroInsane"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\poroInsane.tga:28:28",
	["skip"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\skip.tga:28:28",
	["uuh"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\uuh.tga:28:28",
	["deadNimes"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\deadNimes.tga:28:28",
	["glewpert"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\glewpert.tga:28:28",
	["hesLying"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hesLying.tga:28:28",
	["LALO"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\LALO.tga:28:28",
	["LALOE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\LALOE.tga:28:28",
	["PLAAAY"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\PLAAAY.tga:28:28",
	["Swag"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Swag.tga:28:28",
	["SwagOff"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\SwagOff.tga:28:28",
	["okak"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\okak.tga:28:39",
	["otag"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\otag.tga:28:56",
	["zazaglorp"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\zazaglorp.tga:28:84",
	["FRUNK"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\FRUNK.tga:28:28",
	["rabbit"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\rabbit.tga:28:30",
	["yougotmail"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\yougotmail.tga:28:28",
	["Swagging"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Swagging.tga:28:28",
}


BuhEmotesPack_animation_metadata = {
	--Example
	--["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\EmoteName.tga"] = {["nFrames"] = tt, ["frameWidth"] = xx, ["frameHeight"] = yy, ["imageWidth"]=xx, ["imageHeight"]=yy, ["framerate"] = tt},

	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\pokiLoser.tga"] = {["nFrames"] = 35, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1120, ["framerate"] = 50},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\lule.tga"] = {["nFrames"] = 58, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1856, ["framerate"] = 21},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\PAYUP.tga"] = {["nFrames"] = 130, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4160, ["framerate"] = 20},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\COIN.tga"] = {["nFrames"] = 30, ["frameWidth"] = 35, ["frameHeight"] = 32, ["imageWidth"]= 35, ["imageHeight"]= 960, ["framerate"] = 33},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WalterIsSus.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 960, ["framerate"] = 10},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenNugget.tga"] = {["nFrames"] = 238, ["frameWidth"] = 25, ["frameHeight"] = 32, ["imageWidth"]= 25, ["imageHeight"]= 7616, ["framerate"] = 50},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Speechless.tga"] = {["nFrames"] = 73, ["frameWidth"] = 34, ["frameHeight"] = 32, ["imageWidth"]= 34, ["imageHeight"]= 2336, ["framerate"] = 10},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\BeerTime.tga"] = {["nFrames"] = 53, ["frameWidth"] = 28, ["frameHeight"] = 28, ["imageWidth"]= 28, ["imageHeight"]= 1484, ["framerate"] = 7},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\GETOUTTAHERE.tga"] = {["nFrames"] = 74, ["frameWidth"] = 48, ["frameHeight"] = 32, ["imageWidth"]= 48, ["imageHeight"]= 2368, ["framerate"] = 16},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenTRICKLEIN.tga"] = {["nFrames"] = 60, ["frameWidth"] = 51, ["frameHeight"] = 32, ["imageWidth"]= 51, ["imageHeight"]= 1920, ["framerate"] = 32},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\CoinTime.tga"] = {["nFrames"] = 17, ["frameWidth"] = 28, ["frameHeight"] = 32, ["imageWidth"]= 28, ["imageHeight"]= 544, ["framerate"] = 10},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\creature.tga"] = {["nFrames"] = 41, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1312, ["framerate"] = 9},

    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Gigachad.tga"] = {["nFrames"] = 192, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=8192, ["framerate"] = 24},
    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\huh.tga"] = {["nFrames"] = 93, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=4096, ["framerate"] = 15},
    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docNotL.tga"] = {["nFrames"] = 60, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=2048, ["framerate"] = 25},
    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\NOOO.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=256, ["framerate"] = 15},
    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\buh.tga"] = {["nFrames"] = 159, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=8192, ["framerate"] = 24},
    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\AYAYA.tga"] = {["nFrames"] = 123, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=4096, ["framerate"] = 24},
    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\nymnVibe.tga"] = {["nFrames"] = 128, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=4096, ["framerate"] = 30},
    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\MUGA.tga"] = {["nFrames"] = 112, ["frameWidth"] = 64, ["frameHeight"] = 32, ["imageWidth"]=64, ["imageHeight"]=4096, ["framerate"] = 20},
    ["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\chipichipi.tga"] = {["nFrames"] = 133, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=8192, ["framerate"] = 15},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docL.tga"] = {["nFrames"] = 46, ["frameWidth"] = 64, ["frameHeight"] = 64, ["imageWidth"]=64, ["imageHeight"]=4096, ["framerate"] = 15},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WAYTOOBUH.tga"] = {["nFrames"] = 46, ["frameWidth"] = 45, ["frameHeight"] = 32, ["imageWidth"]=64, ["imageHeight"]=2048, ["framerate"] = 15},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsen.tga"] = {["nFrames"] = 126, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=4096, ["framerate"] = 24},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenMaxLevel.tga"] = {["nFrames"] = 17, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=1024, ["framerate"] = 15},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\veryCat.tga"] = {["nFrames"] = 42, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=2048, ["framerate"] = 2},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\OOOO.tga"] = {["nFrames"] = 125, ["frameWidth"] = 45, ["frameHeight"] = 32, ["imageWidth"]=64, ["imageHeight"]=4096, ["framerate"] = 25},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WHAT.tga"] = {["nFrames"] = 55, ["frameWidth"] = 47, ["frameHeight"] = 32, ["imageWidth"]=64, ["imageHeight"]=2048, ["framerate"] = 20},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docBozo.tga"] = {["nFrames"] = 50, ["frameWidth"] = 64, ["frameHeight"] = 64, ["imageWidth"]=64, ["imageHeight"]=4096, ["framerate"] = 20},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\buhNOW.tga"] = {["nFrames"] = 14, ["frameWidth"] =88 , ["frameHeight"] = 64, ["imageWidth"]=128, ["imageHeight"]=8192, ["framerate"] = 10},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\billyApprove.tga"] = {["nFrames"] = 93, ["frameWidth"] =32 , ["frameHeight"] = 32, ["imageWidth"]=32, ["imageHeight"]=4096, ["framerate"] = 24},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenLaughingAtYou.tga"] = {["nFrames"] = 72, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WeebsOut.tga"] = {["nFrames"] = 34, ["frameWidth"] = 64, ["frameHeight"] = 64, ["imageWidth"]= 64, ["imageHeight"]= 4096, ["framerate"] = 20},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\NOIDONTTHINKSO.tga"] = {["nFrames"] = 124, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\billySmoke.tga"] = {["nFrames"] = 263, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 16384, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docSpin.tga"] = {["nFrames"] = 34, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 75},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hiii.tga"] = {["nFrames"] = 8, ["frameWidth"] = 192, ["frameHeight"] = 64, ["imageWidth"]= 256, ["imageHeight"]= 1024, ["framerate"] = 60},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\docRant.tga"] = {["nFrames"] = 74, ["frameWidth"] = 48, ["frameHeight"] = 32, ["imageWidth"]= 64, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\MAXWIN.tga"] = {["nFrames"] = 292, ["frameWidth"] = 96, ["frameHeight"] = 20, ["imageWidth"]= 128, ["imageHeight"]= 8192, ["framerate"] = 45},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\NOWWHAT.tga"] = {["nFrames"] = 76, ["frameWidth"] = 64, ["frameHeight"] = 32, ["imageWidth"]= 64, ["imageHeight"]= 4096, ["framerate"] = 20},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\plink.tga"] = {["nFrames"] = 59, ["frameWidth"] = 80, ["frameHeight"] = 32, ["imageWidth"]= 128, ["imageHeight"]= 2048, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Scared.tga"] = {["nFrames"] = 55, ["frameWidth"] = 29	, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\confused.tga"] = {["nFrames"] = 110, ["frameWidth"] = 32	, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\floppaHey.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32	, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1024, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\terrypls.tga"] = {["nFrames"] = 71, ["frameWidth"] = 32	, ["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\AINTNOWAY.tga"] = {["nFrames"] = 100, ["frameWidth"] = 39, ["frameHeight"] = 32, ["imageWidth"]= 64, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenCoomer.tga"] = {["nFrames"] = 98, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\DOCING.tga"] = {["nFrames"] = 101, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\DRAMA.tga"] = {["nFrames"] = 64, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\HowAboutYouShutYourMouthUp.tga"] = {["nFrames"] = 175, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 8192, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\IHATEAI.tga"] = {["nFrames"] = 20, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1024, ["framerate"] = 20},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Alienapprove.tga"] = {["nFrames"] = 49, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\MODS.tga"] = {["nFrames"] = 156, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 8192, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\OMEGALULiguess.tga"] = {["nFrames"] = 181, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 8192, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Pepepainsiguess.tga"] = {["nFrames"] = 150, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 8192, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Sneak.tga"] = {["nFrames"] = 14, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1024, ["framerate"] = 30},
	
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Aplonk.tga"] = {["nFrames"] = 60, ["frameWidth"] = 80,["frameHeight"] = 32, ["imageWidth"]= 128, ["imageHeight"]= 2048, ["framerate"] = 20},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Dreiecksmann.tga"] = {["nFrames"] = 23, ["frameWidth"] = 64,["frameHeight"] = 64, ["imageWidth"]= 64, ["imageHeight"]= 2048, ["framerate"] = 60},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Erm.tga"] = {["nFrames"] = 123, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenExplainingHow.tga"] = {["nFrames"] = 102, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 20},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenHoppedIn.tga"] = {["nFrames"] = 144, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 8192, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\hump.tga"] = {["nFrames"] = 21, ["frameWidth"] = 64,["frameHeight"] = 64, ["imageWidth"]= 64, ["imageHeight"]= 2048, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Kronvall.tga"] = {["nFrames"] = 156, ["frameWidth"] = 64,["frameHeight"] = 64, ["imageWidth"]= 64, ["imageHeight"]= 16384, ["framerate"] = 60},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\OHMYGOD.tga"] = {["nFrames"] = 109, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},

	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\WHATTAAHFUCK.tga"] = {["nFrames"] = 50, ["frameWidth"] = 105,["frameHeight"] = 32, ["imageWidth"]= 128, ["imageHeight"]= 2048, ["framerate"] = 13},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\wuh.tga"] = {["nFrames"] = 26, ["frameWidth"] = 328,["frameHeight"] = 128, ["imageWidth"]= 328, ["imageHeight"]= 4096, ["framerate"] = 13},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\tassemble.tga"] = {["nFrames"] = 17, ["frameWidth"] = 384,["frameHeight"] = 128, ["imageWidth"]= 328, ["imageHeight"]= 4096, ["framerate"] = 10},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\tatter.tga"] = {["nFrames"] = 18, ["frameWidth"] = 384,["frameHeight"] = 128, ["imageWidth"]= 328, ["imageHeight"]= 4096, ["framerate"] = 10},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\clappi.tga"] = {["nFrames"] = 29, ["frameWidth"] = 128,["frameHeight"] = 128, ["imageWidth"]= 128, ["imageHeight"]= 4096, ["framerate"] = 24},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\catSigh.tga"] = {["nFrames"] = 60, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\500cigarettes.tga"] = {["nFrames"] = 105, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\catWait.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1024, ["framerate"] = 24},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\ermgamba.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1024, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Ermki.tga"] = {["nFrames"] = 123, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\GULP.tga"] = {["nFrames"] = 42, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 12},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\IHaveBrainDamage.tga"] = {["nFrames"] = 175, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 8192, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\keking.tga"] = {["nFrames"] = 125, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 40},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Pffttt.tga"] = {["nFrames"] = 41, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 15},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\prePffttt.tga"] = {["nFrames"] = 54, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 18},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\vegan.tga"] = {["nFrames"] = 90, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 60},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\wait.tga"] = {["nFrames"] = 120, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 20},
	--["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\YoungMan.tga"] = {["nFrames"] = 52, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenbitrate.tga"] = {["nFrames"] = 126, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 24},
	--["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\YesThisIsTheTwoTimes.tga"] = {["nFrames"] = 105, ["frameWidth"] = 64,["frameHeight"] = 32, ["imageWidth"]= 64, ["imageHeight"]= 4096, ["framerate"] = 60}

	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Aloo.tga"] = {["nFrames"] = 31, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1024, ["framerate"] = 11},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\chicanery.tga"] = {["nFrames"] = 77, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\forsenFaint.tga"] = {["nFrames"] = 51, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\glorpFaint.tga"] = {["nFrames"] = 27, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 1024, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\kok.tga"] = {["nFrames"] = 70, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 60},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Lamonting.tga"] = {["nFrames"] = 118, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 60},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\mhm.tga"] = {["nFrames"] = 9, ["frameWidth"] = 37,["frameHeight"] = 32, ["imageWidth"]= 64, ["imageHeight"]= 512, ["framerate"] = 4},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\nuhuh.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 256, ["framerate"] = 4},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\poroAgony.tga"] = {["nFrames"] = 66, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 24},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\poroInsane.tga"] = {["nFrames"] = 68, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 24},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\skip.tga"] = {["nFrames"] = 45, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 30},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\uuh.tga"] = {["nFrames"] = 41, ["frameWidth"] = 57,["frameHeight"] = 32, ["imageWidth"]= 64, ["imageHeight"]= 2048, ["framerate"] = 24},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\yougotmail.tga"] = {["nFrames"] = 43, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 2048, ["framerate"] = 15},
	["Interface\\AddOns\\TwitchEmotes\\Emotes\\Buhs\\Swagging.tga"] = {["nFrames"] = 116, ["frameWidth"] = 32,["frameHeight"] = 32, ["imageWidth"]= 32, ["imageHeight"]= 4096, ["framerate"] = 20},
}

BuhEmotesPack_emoticons = {
	--Example
	--["EmoteName"] = "EmoteName",

	["pokiLoser"] = "pokiLoser",
	["Cinema"] = "Cinema",
	["kittenlover"] = "kittenlover",
	["Lemon"] = "Lemon",
	["lule"] = "lule",
	["PAYUP"] = "PAYUP",
	["COIN"] = "COIN",
	["Coins"] = "Coins",
	["WalterIsSus"] = "WalterIsSus",
	["forsenNugget"] = "forsenNugget",
	["Speechless"] = "Speechless",
	["bbL"] = "bbL",
	["forsenMissing"] = "forsenMissing",
	["BeerTime"] = "BeerTime",
	["GETOUTTAHERE"] = "GETOUTTAHERE",
	["forsenTRICKLEIN"] = "forsenTRICKLEIN",
	["CoinTime"] = "CoinTime",
	["ome2"] = "ome2",
	["ome"] = "ome",
	["creature"] = "creature",
	["Coinge"] = "Coinge",

    ["buh"] = "buh",
	["Gigachad"] = "Gigachad",
	["Buhh"] = "Buhh",
	["cuteBuhh"] = "cuteBuhh",
	["buhL"] = "buhL",
	["Ted"] = "Ted",
	["huh"] = "huh",
	["docnotL"] = "docnotL",
	["Ogre"] = "Ogre",
	["NOOO"] = "NOOO",
	["Buhsiness"] = "Buhsiness",
	["buhFriend"] = "buhFriend",
	["AYAYA"] = "AYAYA",
	["hesRight"] = "hesRight",
	["nymnVibe"] = "nymnVibe",
	["MUGA"] = "MUGA",
	["chipichipi"] = "chipichipi",
	["corpa"] = "corpa",
	["docL"] = "docL",
	["WAYTOOBUH"] = "WAYTOOBUH",
	["OOOO"] = "OOOO",
	["WHAT"] = "WHAT",
	["forsen"] = "forsen",
	["forsenMaxLevel"] = "forsenMaxLevel",
	["veryCat"] = "veryCat",
	["terryBased"] = "terryBased",
	["docBozo"] = "docBozo",
	["Tomfoolery"] = "Tomfoolery",
	["AmongE"] = "AmongE",
	["buhNOW"] = "buhNOW",
	["Mails"] = "Mails",
	["billyApprove"] = "billyApprove",
	["forsenLaughingAtYou"] = "forsenLaughingAtYou",
	["hesBB"] = "hesBB",
	["eliselis"] = "eliselis",
	["WeebsOut"] = "WeebsOut",
	["glorp"] = "glorp",
	["glorpLove"] = "glorpLove",
	["glebeGlebe"] = "glebeGlebe",
	["NOIDONTTHINKSO"] = "NOIDONTTHINKSO",
	["billySmoke"] = "billySmoke",
	["docSpin"] = "docSpin",
	["hiii"] = "hiii",
	["peachy"] = "peachy",
	["doctorWTF"] = "doctorWTF",
	["Despair"] = "Despair",
	["angrE"] = "angrE",
	["CAUGHT"] = "CAUGHT",
	["happyHobo"] = "happyHobo",
	["FeelsDonkMan"] = "FeelsDonkMan",
	["forsenInsane"] = "forsenInsane",
	["Jackass"] = "Jackass",
	["RaidToday"] = "RaidToday",
	["Rime"] = "Rime",
	["waltuh"] = "waltuh",
	["Waltuhwhite"] = "Waltuhwhite",
	["docRant"] = "docRant",
	["forsenCoomer"] = "forsenCoomer",
	["MAXWIN"] = "MAXWIN",
	["NOWWHAT"] = "NOWWHAT",
	["plink"] = "plink",
	["Scared"] = "Scared",
	["confused"] = "confused",
	["floppaHey"] = "floppaHey",
	["poroSad"] = "poroSad",
	["poroBuff"] = "poroBuff",
	["Roppie"] = "Roppie",
	["sadE"] = "sadE",
	["terrypls"] = "terrypls",
	["AINTNOWAY"] = "AINTNOWAY",
-- v1.3.2	
	["DOCING"] = "DOCING",
	["DRAMA"] = "DRAMA",
	["4House"] = "4House",
	["AlienUnpleased"] = "AlienUnpleased",
	["Dutch"] = "Dutch",
	["Erizel"] = "Erizel",
	["EULKEKUNJEF"] = "EULKEKUNJEF",
	["forsenOhiomaxcape"] = "forsenOhiomaxcape",
	["Hipposham"] = "Hipposham",
	["Hippan"] = "Hippan",
	["KUKLE"] = "KUKLE",
	["LEUL"] = "LEUL",
	["NIME"] = "NIME",
	["ULLE"] = "ULLE",
	["zazabert"] = "zazabert",
	["forsenLevel"] = "forsenLevel",
	["HowAboutYouShutYourMouthUp"] = "HowAboutYouShutYourMouthUp",
	["IHATEAI"] = "IHATEAI",
	["Alienapprove"] = "Alienapprove",
	["Lexmorn"] = "Lexmorn",
	["MODS"] = "MODS",
	["OMEGALULiguess"] = "OMEGALULiguess",
	["Pepepainsiguess"] = "Pepepainsiguess",
	["Sneak"] = "Sneak",
	
	["AlienDisapointedInYou"] = "AlienDisapointedInYou",
	["AlienL"] = "AlienL",
	["angriER"] = "angriER",
	["looking"] = "looking",
	["FRICK"] = "FRICK",
	["LULG"] = "LULG",
	["peepoTalkbutpeepoisnottalking"] = "peepoTalkbutpeepoisnottalking",
	["Pointless"] = "Pointless",
	["Sadeg"] = "Sadeg",
	["Smile"] = "Smile",
	["ta"] = "ta",
	["tuh"] = "tuh",
	["hesRetarded"] = "hesRetarded",
	["Aplonk"] = "Aplonk",
	["Dreiecksmann"] = "Dreiecksmann",
	["Erm"] = "Erm",
	["forsenExplainingHow"] = "forsenExplainingHow",
	["forsenHoppedIn"] = "forsenHoppedIn",
	["hump"] = "hump",
	["Kronvall"] = "Kronvall",
	["ta7"] = "ta7",
	["OHMYGOD"] = "OHMYGOD",

	["WHATTAAHFUCK"] = "WHATTAAHFUCK",
	["wuh"] = "wuh",
	--["tassemble"] = "tassemble",
	--["tatter"] = "tatter",
	["Drunkge"] = "Drunkge",
	["tay"] = "tay",
	["xalatath"] = "xalatath",
	["tah"] = "tah",
	["Blalatath"] = "Blalatath",
	["tatter"] = "tatter",
	["tassemble"] = "tassemble",

	["oopsie"] = "oopsie",
	["clappi"] = "clappi",
	["Despairm"] = "Despairm",
	["er"] = "er",
	["eww"] = "eww",
	["forsenAlright"] = "forsenAlright",
	["hesGripping"] = "hesGripping",
	["ta0"] = "ta0",
	["waiting"] = "waiting",
	["catSigh"] = "catSigh",
	["sus"] = "sus",
	["tainy"] = "tainy",
	["500cigarettes"] = "500cigarettes",
	["catWait"] = "catWait",
	["erm"] = "erm",
	["Ermki"] = "Ermki",
	["GULP"] = "GULP",
	["IHaveBrainDamage"] = "IHaveBrainDamage",
	["keking"] = "keking",
	["Pffttt"] = "Pffttt",
	["prePffttt"] = "prePffttt",
	["vegan"] = "vegan",
	["wait"] = "wait",
	--["YoungMan"] = "YoungMan",
	["forsenbitrate"] = "forsenbitrate",
	--["YesThisIsTheTwoTimes"] = "YesThisIsTheTwoTimes",
	["cokebert"] = "cokebert",
	["crackbert"] = "crackbert",

	["Aloo"] = "Aloo",
	["chicanery"] = "chicanery",
	["forsenFaint"] = "forsenFaint",
	["glorpFaint"] = "glorpFaint",
	["kok"] = "kok",
	["Lamonting"] = "Lamonting",
	["mhm"] = "mhm",
	["nuhuh"] = "nuhuh",
	["poroAgony"] = "poroAgony",
	["poroInsane"] = "poroInsane",
	["skip"] = "skip",
	["uuh"] = "uuh",
	["deadNimes"] = "deadNimes",
	["glewpert"] = "glewpert",
	["hesLying"] = "hesLying",
	["LALO"] = "LALO",
	["LALOE"] = "LALOE",
	["PLAAAY"] = "PLAAAY",
	["Swag"] = "Swag",
	["SwagOff"] = "SwagOff",
	["okak"] = "okak",
	["otag"] = "otag",
	["zazaglorp"] = "zazaglorp",
	["FRUNK"] = "FRUNK",
	["rabbit"] = "rabbit",
	["yougotmail"] = "yougotmail",
	["Swagging"] = "Swagging",
}


-- Ensure TwitchEmotes is loaded
if not TwitchEmotes_defaultpack then
    TwitchEmotes_defaultpack = {}
end
if not TwitchEmotes_animation_metadata then
    TwitchEmotes_animation_metadata = {}
end
if not TwitchEmotes_emoticons then
    TwitchEmotes_emoticons = {}
end

-- Import static emotes
for emoteName, emotePath in pairs(BuhEmotesPack_defaultpack) do
    TwitchEmotes_defaultpack[emoteName] = emotePath
end

-- Import animated emotes metadata
for emotePath, metadata in pairs(BuhEmotesPack_animation_metadata) do
    TwitchEmotes_animation_metadata[emotePath] = metadata
end

-- Import emoticon aliases
for emoteName, alias in pairs(BuhEmotesPack_emoticons) do
    TwitchEmotes_emoticons[emoteName] = alias
end
